name: release

on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        fetch-tags: true
        persist-credentials: false
    - name: Setup uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
    - name: Prepare release notes
      run: uv tool run git-changelog --release-notes > release-notes.md
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release new "${GITHUB_REF_NAME}" \
          --title "${GITHUB_REF_NAME}" \
          --notes-file release-notes.md
